- hosts:  localhost
  connection: local
  become: true

  tasks:
  - name: Create temp directory
    ansible.builtin.tempfile:
      state: directory
      suffix: tmp
  - name: Download ClamAV deb package
    get_url:
      url: https://github.com/Cisco-Talos/clamav/releases/download/clamav-1.2.1/clamav-1.2.1.linux.x86_64.deb
      dest: tmp/clamav-1.2.1.linux.x86_64.deb
      mode: '0644'
  - name: Install ClamAV package
    ansible.builtin.dpkg_selections:
      path: tmp/clamav-1.2.1.linux.x86_64.deb
      state: present
  - name: add ansible user
    user:
      name: admin_ansible
      system: yes
  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_admin_ansible
      dest: /etc/sudoers.d/admin_ansible
      owner: root
      group: root
      mode: 0440
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: admin_ansible
      hour: "*/8"
      job: ansible-pull -o -U https://github.com/smairo/smr-ansible.git workstations/localhost.yml


  #- name: Install packages
  #  apt: name={{item}}
  #  with_items:
  #    - clamav
  #- name: Install ClamAV
  #  package:
  #    state: present
  #    name:
  #    - clamav
  #    - clamd
  #- name: Enable ClamAV service
  #  service:
  #    name: clamd
  #    enabled: True
  #- name: Remove "clamav" package
  #  apt:
  #    name: clamav
  #    state: absent
  #- name: Remove "clamad" package
  #  apt:
  #    name: clamd
  #    state: absent